examples/browser/statics/index.html

Due to inconsistencies in how browsers across different platforms handle the `accept` field of a file input, we need to use file extensions, rather than MIME types, to allow opening PSD files.
Fixes #1

fix(demo): allow opening PSD files on Windows

---

package-lock.json

In particular, this updates [follow-redirects](https://www.npmjs.com/package/follow-redirects) 1.14.7 to 1.14.8 to address a GitHub dependabot alert.
(related advisory: https://github.com/advisories/GHSA-pw2r-vq6v-hr8c)
This package is a dependency of webpack-dev-server, which is used only for local development and therefore should not affect consumers of @webtoon/psd. Nevertheless, we'll update all dependencies just in case.

chore: update all dependencies

---

package.json

fix: update main and types in package.json

---

.github/workflows/publish-demo.yml
README.md

Back in 2022-05-13, we renamed the default branch from `master` to `main`, following [GitHub's guidelines](https://github.com/github/renaming). This PR addresses some issues that we missed:
- Change the branch name filter in the CI script that publishes GitHub Pages (`publish-demo.yml`).
- Update links in `README.md`. While GitHub does redirect them from `../master/..` to `../main/..`, it's probably best not to rely on this behavior.

Rename default branch to 'main'

---

.github/workflows/publish-demo.yml

This fixes the following CI error:
```
webpack 5.73.0 compiled with 3 warnings in 13406 ms
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@fv-az74-828.rg1nhevy3x5uhivy2ou0ehszxf.jx.internal.cloudapp.net>) not allowed
Error: Process completed with exit code 1.
```
The errors were observed in the following runs:
- https://github.com/webtoon/psd/runs/6828152676?check_suite_focus=true
- https://github.com/webtoon/psd/runs/6349346363?check_suite_focus=true
This PR updates the CI script to resolve the issue, based on the following tips:
- …

ci: set fake Git user for deploying

---

README.md
package.json

This PR fixes issues caused by or overlooked in #19.
- Before building the browser example and benchmark web apps for deploying to GitHub Pages, (re)build the library (@webtoon/psd). This ensures that the deployment CI script (`publish-demo.yml`) runs correctly.
- Add and update links to example project sources in README.

Followup fixes for Monorepo PR

---

package-lock.json
packages/psd/package.json

Instead of requiring wasm-pack to be globally available, add it to `devDependencies`. This allows building the project in GitHub's CI environment (which has the Rust toolchain, but not wasm-pack) without further setup.
This should resolve a build script failure caused by #20.

chore: add wasm-pack to devDependencies

---

packages/example-browser/vite.config.ts

This is a follup-up PR for a bug in #20 (17682fb431371e6f30a7566b7dec32601e16b13a) that caused the asset paths for the browser example to be emitted incorrectly.

build: fix base dir of browser-example

---

packages/psd/vite.config.ts

This PR is a follow-up of #20. ESBuild minification causes Vitest to fail for unknown reasons, so we're disabling it when testing.

build: disable minification when testing

---

package.json

- Make `npm run clear` more generic
- Make `npm run release` run the `build` script (so that dependencies can be built in advance)

chore: small fixes to NPM scripts

---

package.json

This PR fixes an oversight in #20, where the NPM `deploy` script does not build the `@webtoon/psd-decoder` package, causing the build to fail for `@webtoon/psd`, `@webtoon/example-browser`, and `@webtoon/benchmark`.

chore: build psd-decoder when deploying

---

README.md
packages/example-node/script.js
packages/psd/src/classes/Group.ts
packages/psd/src/classes/Layer.ts
packages/psd/src/classes/Node.ts
packages/psd/src/classes/NodeBase.ts
packages/psd/src/classes/Psd.ts
packages/psd/src/index.ts

Currently, we export many values including classes (`Layer`, `Group`) and methods (`parse()`). These expose implementation details and enable unsupported workflows (e.g. instantiating a `Group` directly).
To prevent this, we reduced our API surface:
- Remove named export: `parse()` (not to be confused with `Psd.parse()`, which is a static method on the _default-exported_ `Psd` class)
- Only export as types: `Layer`, `Group`
We also refactored our code to continue supporting some workflows (e.g. `traverseNode()`).
Note: We still export enums (`ColorMode`, `Depth`, `GuideDirection`, `SliceOrigin`) by value.

feat!: remove unwanted exports or make them type-only exports

---

packages/psd/src/sections/LayerAndMaskInformation/AdditionalLayerInfo/index.ts

Fix some bugs that caused some PSD files to fail to parse.

fix: parsing errors for some files

---

packages/psd/src/sections/LayerAndMaskInformation/readLayerRecordsAndChannels.ts

Some layers (e.g. gradient fill layers) may have empty channel data. Previously, attempting to skip over the scan lines in such channels resulted in buffer overflow (`RangeError`).
Let's avoid this by limiting the skip amount to the size of the channel data. This ensures that empty channels cannot be "skipped" at all.
Note: This appears to render the layer as a 1x1 empty image. Although this is not ideal, we can't do anything about it. Synthesizing a layer image from its gradient metadata is currently beyond our scope.
Fixes #40

fix: handle empty channel data

---

README.md

AFAIK only the pixel data of the entire image needs the PSD/PSB to be saved with "Maximize Compatibility". I've tested this.
I didn't test for `layer.composite()`. I suspect layers don't need it.
By the way: beautiful library!! I've just tested it with [ZMOK](https://github.com/MARTYR-X-LTD/ZMOK) coming from psd.js and made really noticeable speed improvements. Impressive work 🎉

Psd.composite() note about "Maximize Compatibility"

---

README.md

readme.md web browser example not working.
https://github.com/webtoon/psd/blob/8885f167ac1382a14facea47413dd9fb85bac924/README.md?plain=1#L77-L81
`psdFile.composite` function return `Promise<Uint8ClampedArray>` 
so readme.md example causing error like this
so i added `await` keyword for psdFile.composite async func
```ts
const compositeBuffer = await psdFile.composite(); // composite function return Promise
const imageData = new ImageData(
compositeBuffer,
psdFile.width,
psdFile.height
);
```

Update README.md web browser example code

---

packages/decoder/vite.config.ts
packages/psd/vite.config.ts

Properly generate a source map during build. We were already generating source maps (using `tsc`) for type definitions. However, these only helped our DX and did nothing for our users--because we don't publish the source (*.ts) files, the source maps were broken.
Now we provide a proper source map generated by Vite, so that users can properly debug @webtoon/psd.

build: properly enable source map

---

packages/psd/src/classes/Psd.ts
packages/psd/src/index.ts
packages/psd/src/interfaces/resources/GlobalLight.ts
packages/psd/src/interfaces/resources/ResolutionInfo.ts
packages/psd/src/interfaces/resources/ResourceType.ts
packages/psd/src/interfaces/resources/index.ts
packages/psd/src/sections/ImageResource/index.ts
packages/psd/src/sections/ImageResource/readResolutionInfo.ts
packages/psd/src/utils/bytes.ts
packages/psd/tests/integration/example.test.ts

Hey,
Over the past month we implemented some features in our fork for the upcoming OpenDesign new release. We didn't have time to discuss them with you properly, so let me know if you want these features or not - in case you do, I'll properly refactor the code and add tests :)
This is PR 2/3; implementing additional image resources: resolution info, global light properties.

feature: Implement additional ImageResources

---

README.md
package-lock.json
package.json
packages/benchmark/package.json
packages/decoder/package.json
packages/example-browser/package.json
packages/psd/package.json
packages/psd/vite.config.ts

Notable changes:
- TypeScript: 4.7.3 → 4.8.4
- Vite: 2.9.14 → 3.1.8
- vite-plugin-wasm: 1.0.1 → 3.0.0
- wasm-pack: 0.10.2 → 0.10.3
These are mostly `devDependencies` that shouldn't affect @webtoon/psd.

chore: update dependencies 2022-10-19

---

packages/psd/src/classes/Group.ts
packages/psd/src/classes/Psd.ts
packages/psd/src/index.ts
packages/psd/src/sections/LayerAndMaskInformation/interfaces.ts
packages/psd/src/sections/LayerAndMaskInformation/readLayerRecordsAndChannels.ts
packages/psd/src/utils/object.ts
packages/psd/tests/integration/fillAdjustments.test.ts
packages/psd/tests/integration/placedLayer.test.ts
packages/psd/tests/integration/vectorMask.test.ts

Sorry I didn't make this work when introducing this feature, but I didn't know enough TypeScript. Anyhow, Record type is better here, since it makes checking keys much more efficient.
Also, a couple of additional quality-of-life-changes:
- expose `AliKey` as part of public API,
- expose `additionalProperties` on Group (things like `ArtboardData` are on Group, not Layer).
Let me know WDYT :)

[api change] Make additionalProperties a Record

---

package-lock.json
packages/benchmark/package.json
packages/decoder/Cargo.lock
packages/decoder/Cargo.toml
packages/decoder/package.json
packages/example-browser/package.json
packages/psd/package.json

This PR is a followup to, and should be merged after, #84. It updates TypeScript, Vite, and other packages used for building and testing. It also updates the Rust crates we depend on, and the copy of [ag-psd](https://github.com/Agamnentzar/ag-psd) we use for benchmark comparisons.

Update build-critical dependencies

---

package-lock.json
package.json
packages/benchmark/package.json
packages/decoder/Cargo.lock
packages/decoder/Cargo.toml
packages/decoder/package.json
packages/decoder/src/lib.rs
packages/example-browser/package.json
packages/example-node/package.json
packages/psd/package.json

Updates dependencies to their latest versions
- TypeScript 5.1.3
- Vite (fixes CVE-2023-34092)
- Other dependencies (including Cargo)
We also remove `wee_alloc` to fix the GHSA-rc23-xxgq-x27g warning from dependabot. Our WASM decoder actively allocates memory while decoding images, so `wee_alloc` was unusable for us anyway.

Chore: update dependencies 2023-06

---

package-lock.json
package.json
packages/benchmark/package.json
packages/example-browser/package.json
packages/example-node/package.json

This PR is a follow-up to #89. It addresses the following issues:
- Packages that depend on the local version of @webtoon/psd correctly specify the version as `*`
- Remove [env-cmd](https://github.com/toddbluhm/env-cmd), which is no longer needed for our release process.

Follow-up for #89

---

packages/psd/src/sections/LayerAndMaskInformation/AdditionalLayerInfo/index.ts

I encountered an issue where PSB files containing Smart Object Layers couldn't be opened correctly.
I found that the problem originated from an error in the getAliLengthFieldSizeType() of the Additional Layer Information.
As specified in the Adobe documentation (https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1049436), there was a typographical error in the key "lnk2". 
In addition, during testing, I discovered an unaccounted key "lnkE", which I've also added to the appropriate sections.
To test these changes, I created a PSB file that contains Smart Object Layers. 
Prior to the changes, the file couldn't be opened, but after applying the corrections, the file opened successfully.
I kindly request a review of this pull request.

Bugfix: Fixed issue with file not opening when PSB & Smart Object are present
